version: "3"

services:
  app:
    build: .
    volumes:
      - ./:/src
    command: ["bash"]

  deploy:
    build: .
    volumes:
      - ./:/src
    environment:
      AWS_REGION: $AWS_REGION
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      ClusterNamesCSV_prod: $ClusterNamesCSV_prod
      ClusterNamesCSV_dev: $ClusterNamesCSV_dev
      atLeastServiceDesiredCount: $atLeastServiceDesiredCount
      GITHUB_REF_NAME: $GITHUB_REF_NAME
