# For full config options, check the docs:
#    docs.serverless.com

service: ecs-right-size-cluster

frameworkVersion: ^3.2.0

provider:
  name: aws
  runtime: provided.al2
  timeout: 30
  versionFunctions: false
  memorySize: 128
  logRetentionInDays: 14
  # you can overwrite defaults here
  #  stage: dev
  #  region: us-east-1

  # you can add statements to the Lambda function's IAM Role here
  iam:
    role:
      statements:
      - Effect: "Allow"
        Action:
        - "autoscaling:DescribeAutoScalingGroups"
        - "autoscaling:DescribeLaunchConfigurations"
        - "autoscaling:UpdateAutoScalingGroup"
        - "ec2:DescribeInstances"
        - "ec2:DescribeLaunchTemplates"
        - "ec2:DescribeLaunchTemplateVersions"
        - "ecs:DescribeContainerInstances"
        - "ecs:DescribeServices"
        - "ecs:DescribeTaskDefinition"
        - "ecs:ListContainerInstances"
        - "ecs:ListServices"
        Resource: "*"

  # you can define service wide environment variables here
  environment:
    stage: ${sls:stage}
    namespace: ${self:custom.namespace}

custom:
  namespace: ${self:service}_${sls:stage}

package:
  patterns:
    - '!./**'
    - './bootstrap'

functions:
  ecsRightSizeCluster:
    handler: bootstrap
    events:
    - schedule:
        rate: rate(10 minutes) # every 10 minutes
        input:
          Region: ${env:AWS_REGION}
          ClusterNamesCSV: ${env:ClusterNamesCSV}
    maximumRetryAttempts: 1
